// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/health": {
            "get": {
                "description": "Returns operational metrics, active stream count, and MQTT connectivity status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Check worker health status",
                "responses": {
                    "200": {
                        "description": "Worker is healthy",
                        "schema": {
                            "$ref": "#/definitions/model.HealthStatusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseError-string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.HealthStatus": {
            "type": "object",
            "properties": {
                "active_streams": {
                    "type": "integer"
                },
                "mqtt_connected": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                },
                "worker_id": {
                    "type": "string"
                }
            }
        },
        "model.HealthStatusResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/model.HealthStatus"
                },
                "message": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/model.MetaPagination"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "model.MetaPagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "totalData": {
                    "type": "integer"
                },
                "totalPage": {
                    "type": "integer"
                }
            }
        },
        "model.ResponseError-string": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/model.MetaPagination"
                },
                "path": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Worker Lokal RTSP Relay API",
	Description:      "Local RTSP-to-MediaMTX Stream Relay Worker for Way Kambas Wildlife Surveillance System",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
